image: Visual Studio 2019
version: "1.0.{build}"
shallow_clone: true
skip_tags: true

build_script:
  - cmd: dotnet --version
  - cmd: dotnet run --configuration Release
  
artifacts:
  - path: Localizations.json
    name: Localizations.json

deploy:
  tag: $(appveyor_build_version)
  description: Localizations $(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: 38MnTKwy7ceZJploqUo/J05xeSoguuhTjzINGlatPnHcECbKbKDLt4A5StWW9UFR
  artifact: Localizations.json